version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Moscow"
    assignees:
      - "zedzhen"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Moscow"
    assignees:
      - "zedzhen"

  - package-ecosystem: pre-commit
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Moscow"
    assignees:
      - "zedzhen"
